---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build
      - yarn keygen
      - cp config/config.example.yaml config/config.development.yaml
      - yarn test:cov
---
kind: pipeline
type: ssh
name: promotion-testing

server:
  host: api.w3itch.io
  user: w3itch-testing
  ssh_key:
    from_secret: SSH_ID_RSA

clone:
  disable: true

steps:
  - name: greeting
    commands:
      - echo promotion testing
  - name: check-env
    commands:
      - ifconfig
      - pwd
      - node -v
  - name: list-easyrpg-testing-games
    commands:
      - ls /var/easyrpg/testing/games
  - name: update-config
    commands:
      - echo $VERSION
      - export HOME=/home/w3itch-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-config-for-rollback
      - mv /home/w3itch-testing/w3itch-backend-config /home/w3itch-testing/w3itch-backend-config-for-rollback
      - cd /home/w3itch-testing
      - git clone -b $VERSION --single-branch ssh://git@gitea.w3itch.io:10022/w3itch-crafter/w3itch-backend-config.git
  - name: build
    commands:
      - export HOME=/home/w3itch-testing
      - export PM2_HOME=/home/w3itch-testing/.pm2
      - cd ~
      - ./redeploy.sh

trigger:
  event:
    - promote
  target:
    - testing
---
kind: pipeline
type: ssh
name: rollback-testing

server:
  host: api.w3itch.io
  user: w3itch-testing
  ssh_key:
    from_secret: SSH_ID_RSA

clone:
  disable: true

steps:
  - name: greeting
    commands:
      - echo rollback testing
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: rollback-config
    commands:
      - echo $VERSION
      - export HOME=/home/w3itch-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-config
      - cp -r /home/w3itch-testing/w3itch-backend-config-for-rollback /home/w3itch-testing/w3itch-backend-config
  - name: rollback-project
    commands:
      - export HOME=/home/w3itch-testing
      - export PM2_HOME=/home/w3itch-testing/.pm2
      - cd ~
      - ./rollback.sh

trigger:
  event:
    - rollback
  target:
    - testing
---
kind: pipeline
type: ssh
name: promotion-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

clone:
  disable: true

steps:
  - name: greeting
    commands:
      - echo promotion production
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: update-config
    commands:
      - echo $VERSION
      - export HOME=/home/w3itch
      - rm -rf /home/w3itch/w3itch-backend-config-for-rollback
      - mv /home/w3itch/w3itch-backend-config /home/w3itch/w3itch-backend-config-for-rollback
      - cd /home/w3itch
      - git clone -b $VERSION --single-branch ssh://git@gitea.w3itch.io:10022/w3itch-crafter/w3itch-backend-config.git
  - name: build
    commands:
      - export HOME=/home/w3itch
      - export PM2_HOME=/home/w3itch/.pm2
      - cd ~
      - ./redeploy.sh
trigger:
  event:
    - promote
  target:
    - production

---
kind: pipeline
type: ssh
name: rollback-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

clone:
  disable: true

steps:
  - name: greeting
    commands:
      - echo rollback production
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: rollback-config
    commands:
      - echo $VERSION
      - export HOME=/home/w3itch
      - rm -rf /home/w3itch/w3itch-backend-config
      - cp -r /home/w3itch/w3itch-backend-config-for-rollback /home/w3itch/w3itch-backend-config
  - name: rollback-project
    commands:
      - export HOME=/home/w3itch
      - export PM2_HOME=/home/w3itch/.pm2
      - cd ~
      - ./rollback.sh
trigger:
  event:
    - rollback
  target:
    - production
---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-testing

server:
  host: api.w3itch.io
  user: w3itch-testing
  ssh_key:
    from_secret: SSH_ID_RSA

clone:
  disable: true

steps:
  - name: greeting
    commands:
      - echo deploy testing
  - name: check-env
    commands:
      - ifconfig
      - pwd
      - node -v
  - name: list-easyrpg-testing-games
    commands:
      - ls /var/easyrpg/testing/games
  - name: update-config
    commands:
      - export VERSION=v0.4.1
      - echo $VERSION
      - export HOME=/home/w3itch-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-config-for-rollback
      - mv /home/w3itch-testing/w3itch-backend-config /home/w3itch-testing/w3itch-backend-config-for-rollback
      - cd /home/w3itch-testing
      - git clone -b $VERSION --single-branch ssh://git@gitea.w3itch.io:10022/w3itch-crafter/w3itch-backend-config.git
  - name: build
    commands:
      - export HOME=/home/w3itch-testing
      - export PM2_HOME=/home/w3itch-testing/.pm2
      - cd ~
      - ./redeploy.sh

trigger:
  branch:
    - testing
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push

---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

clone:
  disable: true

steps:
  - name: greeting
    commands:
      - echo deploy production
  - name: check-env
    commands:
      - ifconfig
      - pwd
      - node -v
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: update-config
    commands:
      - export VERSION=v0.4.1
      - echo $VERSION
      - export HOME=/home/w3itch
      - rm -rf /home/w3itch/w3itch-backend-config-for-rollback
      - mv /home/w3itch/w3itch-backend-config /home/w3itch/w3itch-backend-config-for-rollback
      - cd /home/w3itch
      - git clone -b $VERSION --single-branch ssh://git@gitea.w3itch.io:10022/w3itch-crafter/w3itch-backend-config.git
  - name: build
    commands:
      - export HOME=/home/w3itch
      - export PM2_HOME=/home/w3itch/.pm2
      - cd ~
      - ./redeploy.sh

trigger:
  branch:
    - main
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push
---
kind: signature
hmac: 6d86e34079e5b60e13c308c89d30e6dcf98485f03132d94dd7593719e8431a71

...
