---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build
      - yarn keygen
      - cp config/config.example.yaml config/config.development.yaml
      - yarn test:cov
---
kind: pipeline
type: ssh
name: promotion-testing

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo promotion testing
  - name: check-env
    commands:
      - ifconfig
      - pwd
      - node -v
  - name: list-easyrpg-testing-games
    commands:
      - ls /var/easyrpg/testing/games
  - name: update-config
    commands:
      - echo $VERSION
      - export HOME=/home/w3itch-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-config-for-rollback
      - mv /home/w3itch-testing/w3itch-backend-config /home/w3itch-testing/w3itch-backend-config-for-rollback
      - cd /home/w3itch-testing
      - git clone -b $VERSION --single-branch ssh://git@gitea.w3itch.io:10022/w3itch-crafter/w3itch-backend-config.git
  - name: build
    commands:
      - export HOME=/home/w3itch-testing
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch-testing/.pm2
      - pm2 stop w3itch-backend-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-testing-for-rollback
      - mv /home/w3itch-testing/w3itch-backend-testing /home/w3itch-testing/w3itch-backend-testing-for-rollback
      - mkdir /home/w3itch-testing/w3itch-backend-testing
      - cp /home/w3itch/w3itch-backend-config/config/config.development.yaml /home/w3itch-testing/config-testing/
      - cp -r * /home/w3itch-testing/w3itch-backend-testing/
      - cp /home/w3itch-testing/config-testing/* /home/w3itch-testing/w3itch-backend-testing/config/
      - cd /home/w3itch-testing/w3itch-backend-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-testing/thirdparty/games
      - ln -s /var/easyrpg/testing/games /home/w3itch-testing/w3itch-backend-testing/thirdparty/games
      - rm -rf /home/w3itch-testing/w3itch-backend-testing/thirdparty/gencache
      - ln -s /var/easyrpg/testing/gencache /home/w3itch-testing/w3itch-backend-testing/thirdparty/gencache
      - rm -rf /home/w3itch-testing/w3itch-backend-testing/thirdparty/downloads
      - ln -s /var/easyrpg/testing/downloads /home/w3itch-testing/w3itch-backend-testing/thirdparty/downloads
      - rm -rf /home/w3itch-backend-testing/thirdparty/rtp
      - cp -r /var/easyrpg/testing/rtp /home/w3itch-testing/w3itch-backend-testing/thirdparty/rtp
      - yarn typeorm migration:run
      - pm2 restart w3itch-backend-testing --update-env

trigger:
  event:
    - promote
  target:
    - testing
---
kind: pipeline
type: ssh
name: rollback-testing

server:
  host: api.w3itch.io
  user: w3itch-testing
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo rollback testing
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: rollback-config
    commands:
      - echo $VERSION
      - export HOME=/home/w3itch-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-config
      - cp -r /home/w3itch-testing/w3itch-backend-config-for-rollback /home/w3itch-testing/w3itch-backend-config
  - name: rollback-project
    commands:
      - export HOME=/home/w3itch-testing
      - export PM2_HOME=/home/w3itch-testing/.pm2
      - pm2 stop w3itch-backend-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-testing
      - cp -r /home/w3itch-testing/w3itch-backend-testing-for-rollback /home/w3itch-testing/w3itch-backend-testing
      - pm2 restart w3itch-backend-testing --update-env
trigger:
  event:
    - rollback
  target:
    - testing
---
kind: pipeline
type: ssh
name: promotion-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo promotion production
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: update-config
    commands:
      - echo $VERSION
      - export HOME=/home/w3itch
      - rm -rf /home/w3itch/w3itch-backend-config-for-rollback
      - mv /home/w3itch/w3itch-backend-config /home/w3itch/w3itch-backend-config-for-rollback
      - cd /home/w3itch
      - git clone -b $VERSION --single-branch ssh://git@gitea.w3itch.io:10022/w3itch-crafter/w3itch-backend-config.git
  - name: build
    commands:
      - export HOME=/home/w3itch
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 stop w3itch-backend
      - rm -rf /home/w3itch/w3itch-backend-for-rollback
      - mv /home/w3itch/w3itch-backend /home/w3itch/w3itch-backend-for-rollback
      - mkdir /home/w3itch/w3itch-backend
      - cp /home/w3itch/w3itch-backend-config/config/config.production.yaml /home/w3itch/config/
      - cp -r * /home/w3itch/w3itch-backend/
      - cp /home/w3itch/config/* /home/w3itch/w3itch-backend/config/
      - cd /home/w3itch/w3itch-backend
      - rm -rf /home/w3itch/w3itch-backend/thirdparty/games
      - ln -s /var/easyrpg/games /home/w3itch/w3itch-backend/thirdparty/games
      - rm -rf /home/w3itch/w3itch-backend/thirdparty/gencache
      - ln -s /var/easyrpg/gencache /home/w3itch/w3itch-backend/thirdparty/gencache
      - rm -rf /home/w3itch/w3itch-backend/thirdparty/downloads
      - ln -s /var/easyrpg/downloads /home/w3itch/w3itch-backend/thirdparty/downloads
      - rm -rf ./thirdparty/rtp
      - cp -r /var/easyrpg/rtp /home/w3itch/w3itch-backend/thirdparty/rtp
      - yarn typeorm:prod migration:run
      - pm2 restart w3itch-backend --update-env
trigger:
  event:
    - promote
  target:
    - production

---
kind: pipeline
type: ssh
name: rollback-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo rollback production
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: rollback-config
    commands:
      - echo $VERSION
      - export HOME=/home/w3itch
      - rm -rf /home/w3itch/w3itch-backend-config
      - cp -r /home/w3itch/w3itch-backend-config-for-rollback /home/w3itch/w3itch-backend-config
  - name: rollback-project
    commands:
      - export HOME=/home/w3itch
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 stop w3itch-backend
      - rm -rf /home/w3itch/w3itch-backend
      - cp -r /home/w3itch/w3itch-backend-for-rollback /home/w3itch/w3itch-backend
      - pm2 restart w3itch-backend --update-env
trigger:
  event:
    - rollback
  target:
    - production
---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-testing

server:
  host: api.w3itch.io
  user: w3itch-testing
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo deploy testing
  - name: check-env
    commands:
      - ifconfig
      - pwd
      - node -v
  - name: list-easyrpg-testing-games
    commands:
      - ls /var/easyrpg/testing/games
  - name: update-config
    commands:
      - export VERSION=v0.4.0-1
      - echo $VERSION
      - export HOME=/home/w3itch-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-config-for-rollback
      - mv /home/w3itch-testing/w3itch-backend-config /home/w3itch-testing/w3itch-backend-config-for-rollback
      - cd /home/w3itch-testing
      - git clone -b $VERSION --single-branch ssh://git@gitea.w3itch.io:10022/w3itch-crafter/w3itch-backend-config.git
  - name: build
    commands:
      - export HOME=/home/w3itch-testing
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch-testing/.pm2
      - pm2 stop w3itch-backend-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-testing-for-rollback
      - mv /home/w3itch-testing/w3itch-backend-testing /home/w3itch-testing/w3itch-backend-testing-for-rollback
      - mkdir /home/w3itch-testing/w3itch-backend-testing
      - cp /home/w3itch-testing/w3itch-backend-config/config/config.development.yaml /home/w3itch-testing/config-testing/
      - cp -r * /home/w3itch-testing/w3itch-backend-testing/
      - cp /home/w3itch-testing/config-testing/* /home/w3itch-testing/w3itch-backend-testing/config/
      - cd /home/w3itch-testing/w3itch-backend-testing
      - rm -rf /home/w3itch-testing/w3itch-backend-testing/thirdparty/games
      - ln -s /var/easyrpg/testing/games /home/w3itch-testing/w3itch-backend-testing/thirdparty/games
      - rm -rf /home/w3itch-testing/w3itch-backend-testing/thirdparty/gencache
      - ln -s /var/easyrpg/testing/gencache /home/w3itch-testing/w3itch-backend-testing/thirdparty/gencache
      - rm -rf /home/w3itch-testing/w3itch-backend-testing/thirdparty/downloads
      - ln -s /var/easyrpg/testing/downloads /home/w3itch-testing/w3itch-backend-testing/thirdparty/downloads
      - rm -rf /home/w3itch-backend-testing/thirdparty/rtp
      - cp -r /var/easyrpg/testing/rtp /home/w3itch-testing/w3itch-backend-testing/thirdparty/rtp
      - yarn typeorm migration:run
      - pm2 restart w3itch-backend-testing --update-env

trigger:
  branch:
    - testing
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push

---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo deploy production
  - name: check-env
    commands:
      - ifconfig
      - pwd
      - node -v
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: update-config
    commands:
      - export VERSION=v0.4.0-1
      - echo $VERSION
      - export HOME=/home/w3itch
      - rm -rf /home/w3itch/w3itch-backend-config-for-rollback
      - mv /home/w3itch/w3itch-backend-config /home/w3itch/w3itch-backend-config-for-rollback
      - cd /home/w3itch
      - git clone -b $VERSION --single-branch ssh://git@gitea.w3itch.io:10022/w3itch-crafter/w3itch-backend-config.git
  - name: build
    commands:
      - export HOME=/home/w3itch
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 stop w3itch-backend
      - rm -rf /home/w3itch/w3itch-backend-for-rollback
      - mv /home/w3itch/w3itch-backend /home/w3itch/w3itch-backend-for-rollback
      - mkdir /home/w3itch/w3itch-backend
      - cp /home/w3itch/w3itch-backend-config/config/config.production.yaml /home/w3itch/config/
      - cp -r * /home/w3itch/w3itch-backend/
      - cp /home/w3itch/config/* /home/w3itch/w3itch-backend/config/
      - cd /home/w3itch/w3itch-backend
      - rm -rf /home/w3itch/w3itch-backend/thirdparty/games
      - ln -s /var/easyrpg/games /home/w3itch/w3itch-backend/thirdparty/games
      - rm -rf /home/w3itch/w3itch-backend/thirdparty/gencache
      - ln -s /var/easyrpg/gencache /home/w3itch/w3itch-backend/thirdparty/gencache
      - rm -rf /home/w3itch/w3itch-backend/thirdparty/downloads
      - ln -s /var/easyrpg/downloads /home/w3itch/w3itch-backend/thirdparty/downloads
      - rm -rf /home/w3itch-backend-testing/thirdparty/rtp
      - cp -r /var/easyrpg/rtp /home/w3itch/w3itch-backend/thirdparty/rtp
      - yarn typeorm:prod migration:run
      - pm2 restart w3itch-backend --update-env

trigger:
  branch:
    - main
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push
---
kind: signature
hmac: 41ba022e5e5a9d912930beeaf6811a3ae7eda48a690fb1850068880fb33d1614

...
